Fix eslint missing next config error
The eslint config is trying to load a next eslint config that is missing and that we don't need : 
```
Error: Failed to load parser './parser.js' declared in '.eslintrc.js » eslint-config-acme » eslint-config-next': Cannot find module 'next/dist/compiled/babel/eslint-parser'
```