Bug fix on with-docker (#7915)
### Description

- moved content of `@repo/jest-presets` package one level up and out of
/jest directory for better accessibility. (in order to import the jest
presets like `@repo/jest-presets/node` instead of
`@repo/jest-presets/jest/node` )
- added `@types/node` to `@repo/logger` package and applied it in
`types` of tsconfig.json to fix the error:
```
Cannot find name 'global'.
jest.spyOn(global.console, "log");
            ^^^^
```
- removed duplicate tsconfig.json from __tests__ as they are not needed.
- added "DOM" to `lib` of `@repo/logger` to fix the error:
```
Cannot find name 'console'. Do you need to change your target library? 
Try changing the 'lib' compiler option to include 'dom'.
```
- added type to the createServer function to fix the error:
```
The inferred type of 'createServer' cannot be named without a reference to 
'.pnpm/@types+express-serve-static-core@4.19.0/node_modules/@types/express-serve-static-core'. 
This is likely not portable. A type annotation is necessary.
```
- replaced `toBeCalled` as it's been deprecated
- change `healthz` to `status` for consistency between examples and also
to fix the typo of `healthz`
- improved React imports by importing `ChangeEvent` and `FormEvent`
instead of using them as `React.ChangeEvent` and `React.FormEvent`
- update the main `README.md` to have updated apps and packages
informations


### Testing Instructions

Running `npx create-turbo@latest -e with-docker` and then both `pnpm
dev` and `pnpm test` should work fine and tests should pass.

---------

Co-authored-by: Anthony Shew <anthony.shew@vercel.com>