swc-ast-explorer: Fix AST printing (#502)
After some upgrade, we needed to wrap our parse in a `GLOBALS.set()`.

The old code was giving:

```bash
$ echo 'a["length"]' | RUST_BACKTRACE=1 cargo run -p swc-ast-explorer
     Running `target/debug/swc-ast-explorer`
thread 'main' panicked at '`swc_common::GLOBALS` is required for this operation', /Users/jridgewell/.cargo/registry/src/github.com-1ecc6299db9ec823/swc-0.231.13/src/lib.rs:254:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e7119a0300b87a3d670408ee8e847c6821b3ae80/library/std/src/panicking.rs:556:5
   1: core::panicking::panic_fmt
             at /rustc/e7119a0300b87a3d670408ee8e847c6821b3ae80/library/core/src/panicking.rs:142:14
   2: swc::Compiler::run
             at /Users/jridgewell/.cargo/registry/src/github.com-1ecc6299db9ec823/swc-0.231.13/src/lib.rs:254:9
   3: swc::Compiler::parse_js
             at /Users/jridgewell/.cargo/registry/src/github.com-1ecc6299db9ec823/swc-0.231.13/src/lib.rs:372:23
   4: swc_ast_explorer::main::{{closure}}
             at ./crates/swc-ast-explorer/src/main.rs:46:19
   5: swc_error_reporters::handler::try_with_handler::{{closure}}
             at /Users/jridgewell/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_error_reporters-0.13.5/src/handler.rs:104:40
   6: scoped_tls::ScopedKey<T>::set
             at /Users/jridgewell/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
   7: better_scoped_tls::ScopedKey<T>::set
             at /Users/jridgewell/.cargo/registry/src/github.com-1ecc6299db9ec823/better_scoped_tls-0.1.0/src/lib.rs:55:9
   8: swc_error_reporters::handler::try_with_handler
             at /Users/jridgewell/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_error_reporters-0.13.5/src/handler.rs:104:15
   9: swc_ast_explorer::main
             at ./crates/swc-ast-explorer/src/main.rs:40:15
  10: core::ops::function::FnOnce::call_once
             at /rustc/e7119a0300b87a3d670408ee8e847c6821b3ae80/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```