Downgrade indexmap and serde_yaml (#2657)
The latest version cause circular reference issue while compiling with next-rs wasm crate.

```
error: cyclic package dependency: package `indexmap v1.9.1` depends on itself. Cycle:
package `indexmap v1.9.1`
    ... which satisfies dependency `indexmap = "^1.5.2"` of package `serde_json v1.0.87`
    ... which satisfies dependency `serde_json = "^1.0"` of package `wasm-bindgen v0.2.83`
    ... which satisfies dependency `wasm-bindgen = "^0.2.83"` of package `js-sys v0.3.60`
    ... which satisfies dependency `js-sys = "^0.3"` of package `getrandom v0.2.8`
    ... which satisfies dependency `getrandom = "^0.2.3"` of package `ahash v0.7.6`
    ... which satisfies dependency `ahash = "^0.7.0"` of package `hashbrown v0.12.3`
    ... which satisfies dependency `hashbrown = "^0.12"` of package `indexmap v1.9.1`
    ... which satisfies dependency `indexmap = "^1.0.2"` of package `gimli v0.26.2`
    ... which satisfies dependency `gimli = "^0.26"` of package `addr2line v0.17.0`
```