chore: Update to Rust 1.96.0
unfortunately, I wasn't able to run clippy here due to strange error appearing in mitsein dependency

```
error[E0252]: the name `Deserialize` is defined multiple times
--> ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/mitsein-0.4.1/src/lib.rs:341:22
|
340 |     ::serde::{Deserialize, Serialize},
|               ----------- previous import of the macro `Deserialize` here
341 |     ::serde_derive::{Deserialize, Serialize},
|                      ^^^^^^^^^^^--
|                      |
|                      `Deserialize` reimported here
|                      help: remove unnecessary import
|
= note: `Deserialize` must be defined only once in the macro namespace of this module

error[E0252]: the name `Serialize` is defined multiple times
--> ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/mitsein-0.4.1/src/lib.rs:341:35
|
340 |     ::serde::{Deserialize, Serialize},
|                            --------- previous import of the macro `Serialize` here
341 |     ::serde_derive::{Deserialize, Serialize},
|                                   ^^^^^^^^^ `Serialize` reimported here
|
= note: `Serialize` must be defined only once in the macro namespace of this module
```