nextest.toml update to next-dev-tests and add retries (#3456)
This updates nextest.toml to use the new package name for next-dev
tests, `next-dev-tests` and adds up to 2 additional retries (for a total
of 3 attempts) since these tests tend to be flakey.

**Note**: This requires `cargo-nextest` version 0.9.49, which includes a
fix for https://github.com/nextest-rs/nextest/issues/762. Otherwise, you
may receive an error when running nextest like:

```
error: failed to parse nextest config at `path/to/.config/nextest.toml`

Caused by:
  profile.default.overrides[0].leak-timeout: invalid type: string "500ms", expected struct Duration

Caused by:
  invalid type: string "500ms", expected struct Duration
```

Test Plan: Temporarily changed `slow-timeout` to `0s` and verified the
override selected next-dev tests by marking them as slow.