chore(examples): fix `pnpm typecheck` in `kitchen-sink` example
> error TS5095: Option 'bundler' can only be used when 'module' is set to 'es2015' or later.

This project doesn't use the `tsc` emit so it should be fine to not set
`'module'`