CSS modules shim (#490)
At the moment, whenever SSR encounters a CSS module, it will likely crash with the following error:

```
TypeError: Cannot read properties of undefined (reading 'someClassName')
```

This is because CSS module support is currently unimplemented. In order to surface other potential errors while waiting
on CSS modules implementation, I've implemented a Proxy-based shim that will always return a string whenever a CSS
module export object is indexed.

There are known issues with this implementation:

- Only .module.css files should be considered CSS modules and EcmascriptChunkPlaceable;
- Could have used `embed_file!`

But since this is intended as a temporary workaround, it's probably good enough.

An example error this helped surface: we currently don't expose a polyfill for `fetch` in Node.js (https://cs.github.com/vercel/next.js/blob/3d499a627f49b911b30120df4e2e39e998d6273b/packages/next/server/node-polyfill-fetch.js?q=fetch#L10)