cli: internal: ffi: Fix missing library
go-turbo requires libgit2 at linkage as follows:

  /usr/bin/ld: /home/shohei/pkgbuilds/turbo/src/turbo-1.8.5/cli/internal/ffi/libturborepo_ffi_linux_amd64.a(git2-c77affaa1e7e43cb.git2.dccd2a89-cgu.13.rcgu.o): in function `git2::remote_callbacks::credentials_cb::{closure#0}::{closure#2}':
  /home/shohei/.cargo/registry/src/index.crates.io-6f17d22bba15001f/git2-0.16.1/src/remote_callbacks.rs:293: undefined reference to `git_error_set_str'
  ...snip...

Signed-off-by: Shohei Maruyama <cheat.sc.linux@outlook.com>