revert workspace dependency to allow building correctly (#4103)
### Description

Cargo always uses default features for workspace dependencies, so we
can't use that here. See also comment.

### Testing Instructions

```
$ cargo tree -p next-binding -i openssl --target x86_64-unknown-linux-gnu -e features
error: package ID specification `openssl` did not match any packages
```